### ISSUE TITLE
Add handling checksum for addresses

### ISSUE THREAD

**Issue by ethedev** [yam-finance/degenerative-v2#196]
After reading from asset json and generally everywhere, convert addresses to what is needed according to the function that is using it, for subgraph lowercasing it is needed for example you can lower case the checksummed address before passing it to subgraph.

**Comment by rossgalloway** [comment]
This seems to be causing an issue with the sushiswap links. Links with no capitalization do not populate the tokens when Sushiswap opens.

So this link works to populate: https://app.sushi.com/add/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0xfc10b3A8011B00489705EF1Fc00D0e501106cB1D

But this link doesnt: https://app.sushi.com/add/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2-0xfc10b3a8011b00489705ef1fc00d0e501106cb1d

So it seems like we are going to need to keep capitalization in the addresses when linking out, but remove it for other operations like pulling data from the Graph.

**Comment by rossgalloway** [comment]
sorry, I was mistaken in thinking capitalization makes a difference when dealing with sushiswap. It doesn't. The problem is the dash (-) between the 2 token addresses.  This should be changed to a forward slash (/) as you see in the second example above. 

like this: https://app.sushi.com/add/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0xfc10b3A8011B00489705EF1Fc00D0e501106cB1D

**Comment by ethedev** [comment]
> sorry, I was mistaken in thinking capitalization makes a difference when dealing with sushiswap. It doesn't. The problem is the dash (-) between the 2 token addresses. This should be changed to a forward slash (/) as you see in the second example above.
> 
> like this: https://app.sushi.com/add/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0xfc10b3A8011B00489705EF1Fc00D0e501106cB1D

ok, that is a separate issue and i assume its happening when you click the "Provide Liquidity" link, pushing a fix now
