### ISSUE TITLE
Breadcrumbs alignment and padding

### ISSUE THREAD

**Issue by ghost** [yam-finance/degenerative-v2#34]
### Description:
The breadcrumbs are not aligned on mobile view and have not enough padding on the top.

### To Reproduce:
1. Go to https://v2develop.degenerative.finance/portfolio
2. Resize to mobile (at least 721 x 1224)
3. Look at the breadcrumbs

### Expected behavior:
The breadcrumbs should be on one line and there should be enough padding on top of the component.

### Devices:
- Smartphone: [yes]

**Comment by ethedev** [comment]
@byterose can you share screenshot how you see that?

**Comment by ghost** [comment]
> @byterose can you share screenshot how you see that?

It looks like this has been fixed. I will therefore close this issue

**Comment by ethedev** [comment]
are you referring to this, if so then no it hasnt been fixed, if you have other scenarios of screenshots please add it


<img width="141" alt="issue" src="https://user-images.githubusercontent.com/2432272/116048014-ca4f7c00-a685-11eb-838e-9c8be8035af7.PNG">

**Comment by ghost** [comment]
> are you referring to this, if so then no it hasnt been fixed, if you have other scenarios of screenshots please add it
> 
> <img alt="issue" width="141" src="https://user-images.githubusercontent.com/2432272/116048014-ca4f7c00-a685-11eb-838e-9c8be8035af7.PNG">

No, I was not referring to this, but it looks like this is another issue so let's keep this open.

**Comment by ethedev** [comment]
@byterose there is some issue with the space that exist on the top of the breadcrumbs 

- <img width="187" alt="2" src="https://user-images.githubusercontent.com/2432272/117533055-a5e78e00-affb-11eb-9141-4e7c6598dfc6.PNG">
- <img width="266" alt="1" src="https://user-images.githubusercontent.com/2432272/117533054-a4b66100-affb-11eb-9b3c-9305b7af478b.PNG">

**Comment by ghost** [comment]
Updated and merged.

**Comment by ethedev** [comment]
I see 2 different margin that are being used, any idea why? it should be the same for both

**Comment by ethedev** [comment]
and this doesnt look good, if you didntt connect yet
- <img width="181" alt="space" src="https://user-images.githubusercontent.com/2432272/117569307-2a0e4400-b0d6-11eb-9c78-341cd61d9756.PNG">

**Comment by ghost** [comment]
> I see 2 different margin that are being used, any idea why? it should be the same for both

That's because the logo is responsive and the padding changes. Therefore we also need two different margins for the connect button.

**Comment by ethedev** [comment]
> > I see 2 different margin that are being used, any idea why? it should be the same for both
> 
> That's because the logo is responsive and the padding changes. Therefore we also need two different margins for the connect button.

that has nothing to do with padding changes and even if the padding is changing the margin of the breadcrumbs should be independent and should have the same exact spacing on normal and responsive views, which also has nothing to do with the connect button

**Comment by ind-igo** [comment]
Can we close?

**Comment by ethedev** [comment]
@blokku-chan @sali0 everything on this was handled?
