### ISSUE TITLE
Resizing the window breaks the page

### ISSUE THREAD

**Issue by ghost** [yam-finance/degenerative-v2#95]
### Description:
Resizing the window breaks the page

### Screenshots:
<img width="582" alt="Screenshot 2021-05-13 at 20 46 27" src="https://user-images.githubusercontent.com/77129089/118172221-6ae6bf80-b42c-11eb-94cb-b5b75a35ab28.png">

**Comment by nateawelch** [comment]
![Screenshot from 2021-05-13 15-25-57](https://user-images.githubusercontent.com/706153/118176623-a74ff680-b3ff-11eb-977c-6982ef14f596.png)
