### ISSUE TITLE
Collateral wETH input shows the wrong data

### ISSUE THREAD

**Issue by ghost** [yam-finance/degenerative-v2#98]
### Description:
When clicking on max wETH collateral button I get a wrong number.
In my example I had 8000 wETH but it is displaying 9000, even if I clear the field and reload the site.

### To Reproduce:
1. Go to 'synths/uGas/JUN21/manage'

### Screenshots:
<img width="171" alt="Screenshot 2021-05-13 at 20 59 58" src="https://user-images.githubusercontent.com/77129089/118173864-67543800-b42e-11eb-8dd8-82678b8bd8fb.png">

**Comment by ind-igo** [comment]
Not sure how you got to this state. If you had a previous position, then the max button will add all of the WETH in your wallet to the text field. The text field will then display your WETH in wallet + WETH in your position.
